spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mariadb://localhost:3307 /identity_service
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identity